### ISSUE TITLE
deploy error

### ISSUE THREAD

**Issue by vstevenson** [dcm4che/dcm4chee-arc-cdi#21]
any help about the following error

Request
{
    "address" => [("deployment" => "dcm4chee-arc-ear-4.5.0-SNAPSHOT-mysql.ear")],
    "operation" => "deploy"
}

Response

Internal Server Error
{
    "outcome" => "failed",
    "failure-description" => {"JBAS014771: Services with missing/unavailable dependencies" => [
        "jboss.naming.context.java.comp.\"dcm4chee-arc-ear-4.5.0-SNAPSHOT-mysql\".\"dcm4chee-arc-noneiocm-4.5.0-SNAPSHOT\".NoneIOCMChangeRequestorServiceEJB.env.\"org.dcm4chee.archive.noneiocm.impl.NoneIOCMChangeRequestorServiceEJB\".noneiocmQueue is missing [jboss.naming.context.java.queue.noneiocm]",
        "jboss.naming.context.java.comp.\"dcm4chee-arc-ear-4.5.0-SNAPSHOT-mysql\".\"dcm4chee-arc-store-remember-4.5.0-SNAPSHOT\".StoreAndRememberEJB.env.\"org.dcm4chee.archive.store.remember.impl.StoreAndRememberEJB\".storeAndRememberQueue is missing [jboss.naming.context.java.queue.storeremember]"
    ]},
    "rolled-back" => true
}

**Comment by Hesham-Elbadawi** [comment]
Hi,
You need to configure the queues in your jboss config.
Check the cli script in the jboss config in the archive assembly package

Kind Regards,

MSc. Hesham Elbadawi | Agfa HealthCare
R&D Software Developer | HE/R&D Impax EE
T  +43189966 315 | F  +43189966 110 | M +4369910928505

Agfa HealthCare GmbH, Diefenbachgasse 35, 1150 Wien, Austria
http://www.agfahealthcare.com
http://blog.agfahealthcare.com
Geschäftsführer: Dkfm. Winfried Post | Sitz der Gesellschaft: Wien, Handelsgericht Wien, FN 56704p | UID ATU15133905
Click on link to read important disclaimer: http://www.agfahealthcare.com/maildisclaimer

**Comment by vstevenson** [comment]
thanks

**Comment by vstevenson** [comment]
Its working now
thanks again
